### ISSUE TITLE
Implement report card style

### ISSUE THREAD

**Issue by BergkampHUN** [BergkampHUN/project-aurora#6]
### Tasks

- [x] Use prime-ng accordion component (https://www.primefaces.org/primeng/accordion) for the list
- [x] For the accordion use the "Custom Content at Headers" section.
- [ ] In the accordion header the ORINV links should open in new browser tabs
- [x] For the doughnut chart use the prime-ng doughnut component (https://www.primefaces.org/primeng/chart/doughnut)
- [x] For the date chooser use the prime-ng splitbutton component  (https://www.primefaces.org/primeng/splitbutton)
- [ ] The card should have an "Input parameter" where you can set to show/hide the date selector
- [ ] The "refresh" buttons at the tracked times should be buttons.

**Comment by BergkampHUN** [comment]
Implemented some parts, but due to the requirement changes these points are not valid anymore. Closing this ticket and the missing ones will be created later in a separated one.
